# Generated by Django 3.0.3 on 2020-02-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
    ]
